baseURL = "https://blog.powwow787.xyz/"
languageCode = "en-us"
title = "파우와우의 블로그"
theme = "PaperMod"
buildDrafts = true
relativeURLs = false      # 보통 false가 절대경로 생성
canonifyURLs = true       # true면 .Permalink가 절대 URL 생성

[pagination]
  pagerSize = 5

[params]
  # home-info mode
  comments = true
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowToc = true
  TocOpen = false

  [params.homeInfoParams]
    Title = "파우와우의 블로그"
    Content = "나의 로그"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/powwow78"

[menu]

  [[menu.main]]
    identifier = "categories"
    name = "categories"
    url = "/categories/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = 20

[caches]
  [caches.images]
    dir = ":cacheDir/images"
